// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudFinancialServicesV1
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc

func sample(
  client: AMLClient, projectNumId: String, locationId: String, instanceId: String,
  engineConfigId: String
) async throws {
  let poller = try await client.deleteEngineConfig(
    withPolling: DeleteEngineConfigRequest()
      .with {
        $0.name =
          "projects/\(projectNumId)/locations/\(locationId)/instances/\(instanceId)/engineConfigs/\(engineConfigId)"
      }
  )
  try await poller.wait()
  print("Success")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudFinancialServicesV1.AMLClient()
      try await sample(
        client: client, projectNumId: "[placeholder]", locationId: "[placeholder]",
        instanceId: "[placeholder]", engineConfigId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
