// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol AMLStub: Sendable {
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListInstancesResponse

    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Instance

    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importRegisteredParties(
      request: ImportRegisteredPartiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportRegisteredParties(
      request: ExportRegisteredPartiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listDatasets(
      request: ListDatasetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListDatasetsResponse

    func getDataset(
      request: GetDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Dataset

    func createDataset(
      request: CreateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateDataset(
      request: UpdateDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listModels(
      request: ListModelsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListModelsResponse

    func getModel(
      request: GetModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Model

    func createModel(
      request: CreateModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateModel(
      request: UpdateModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportModelMetadata(
      request: ExportModelMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteModel(
      request: DeleteModelRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listEngineConfigs(
      request: ListEngineConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListEngineConfigsResponse

    func getEngineConfig(
      request: GetEngineConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.EngineConfig

    func createEngineConfig(
      request: CreateEngineConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEngineConfig(
      request: UpdateEngineConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportEngineConfigMetadata(
      request: ExportEngineConfigMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEngineConfig(
      request: DeleteEngineConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getEngineVersion(
      request: GetEngineVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.EngineVersion

    func listEngineVersions(
      request: ListEngineVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListEngineVersionsResponse

    func listPredictionResults(
      request: ListPredictionResultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListPredictionResultsResponse

    func getPredictionResult(
      request: GetPredictionResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.PredictionResult

    func createPredictionResult(
      request: CreatePredictionResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updatePredictionResult(
      request: UpdatePredictionResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportPredictionResultMetadata(
      request: ExportPredictionResultMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePredictionResult(
      request: DeletePredictionResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listBacktestResults(
      request: ListBacktestResultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListBacktestResultsResponse

    func getBacktestResult(
      request: GetBacktestResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.BacktestResult

    func createBacktestResult(
      request: CreateBacktestResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateBacktestResult(
      request: UpdateBacktestResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportBacktestResultMetadata(
      request: ExportBacktestResultMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteBacktestResult(
      request: DeleteBacktestResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
