// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class AMLRetry: AMLStub {
    let inner: any AMLStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any AMLStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func updateInstance(
      request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInstanceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func importRegisteredParties(
      request: ImportRegisteredPartiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportRegisteredPartiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importRegisteredParties(request: r, options: o)
        })
    }

    public func exportRegisteredParties(
      request: ExportRegisteredPartiesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportRegisteredPartiesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportRegisteredParties(request: r, options: o)
        })
    }

    public func listDatasets(
      request: ListDatasetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListDatasetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDatasetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListDatasetsResponse
          in
          return try await self.inner.listDatasets(request: r, options: o)
        })
    }

    public func getDataset(
      request: GetDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Dataset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.Dataset
          in
          return try await self.inner.getDataset(request: r, options: o)
        })
    }

    public func createDataset(
      request: CreateDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDataset(request: r, options: o)
        })
    }

    public func updateDataset(
      request: UpdateDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDataset(request: r, options: o)
        })
    }

    public func deleteDataset(
      request: DeleteDatasetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDatasetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDataset(request: r, options: o)
        })
    }

    public func listModels(
      request: ListModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListModelsResponse
          in
          return try await self.inner.listModels(request: r, options: o)
        })
    }

    public func getModel(
      request: GetModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.Model {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.Model
          in
          return try await self.inner.getModel(request: r, options: o)
        })
    }

    public func createModel(
      request: CreateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createModel(request: r, options: o)
        })
    }

    public func updateModel(
      request: UpdateModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateModel(request: r, options: o)
        })
    }

    public func exportModelMetadata(
      request: ExportModelMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportModelMetadataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportModelMetadata(request: r, options: o)
        })
    }

    public func deleteModel(
      request: DeleteModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteModel(request: r, options: o)
        })
    }

    public func listEngineConfigs(
      request: ListEngineConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListEngineConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEngineConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListEngineConfigsResponse
          in
          return try await self.inner.listEngineConfigs(request: r, options: o)
        })
    }

    public func getEngineConfig(
      request: GetEngineConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.EngineConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEngineConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.EngineConfig
          in
          return try await self.inner.getEngineConfig(request: r, options: o)
        })
    }

    public func createEngineConfig(
      request: CreateEngineConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEngineConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createEngineConfig(request: r, options: o)
        })
    }

    public func updateEngineConfig(
      request: UpdateEngineConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateEngineConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateEngineConfig(request: r, options: o)
        })
    }

    public func exportEngineConfigMetadata(
      request: ExportEngineConfigMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportEngineConfigMetadataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportEngineConfigMetadata(request: r, options: o)
        })
    }

    public func deleteEngineConfig(
      request: DeleteEngineConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEngineConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteEngineConfig(request: r, options: o)
        })
    }

    public func getEngineVersion(
      request: GetEngineVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.EngineVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEngineVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.EngineVersion
          in
          return try await self.inner.getEngineVersion(request: r, options: o)
        })
    }

    public func listEngineVersions(
      request: ListEngineVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListEngineVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEngineVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListEngineVersionsResponse
          in
          return try await self.inner.listEngineVersions(request: r, options: o)
        })
    }

    public func listPredictionResults(
      request: ListPredictionResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListPredictionResultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPredictionResultsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListPredictionResultsResponse
          in
          return try await self.inner.listPredictionResults(request: r, options: o)
        })
    }

    public func getPredictionResult(
      request: GetPredictionResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.PredictionResult {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPredictionResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.PredictionResult
          in
          return try await self.inner.getPredictionResult(request: r, options: o)
        })
    }

    public func createPredictionResult(
      request: CreatePredictionResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePredictionResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPredictionResult(request: r, options: o)
        })
    }

    public func updatePredictionResult(
      request: UpdatePredictionResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePredictionResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePredictionResult(request: r, options: o)
        })
    }

    public func exportPredictionResultMetadata(
      request: ExportPredictionResultMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportPredictionResultMetadataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportPredictionResultMetadata(request: r, options: o)
        })
    }

    public func deletePredictionResult(
      request: DeletePredictionResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePredictionResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePredictionResult(request: r, options: o)
        })
    }

    public func listBacktestResults(
      request: ListBacktestResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.ListBacktestResultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBacktestResultsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.ListBacktestResultsResponse
          in
          return try await self.inner.listBacktestResults(request: r, options: o)
        })
    }

    public func getBacktestResult(
      request: GetBacktestResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFinancialServicesV1.BacktestResult {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBacktestResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudFinancialServicesV1.BacktestResult
          in
          return try await self.inner.getBacktestResult(request: r, options: o)
        })
    }

    public func createBacktestResult(
      request: CreateBacktestResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBacktestResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBacktestResult(request: r, options: o)
        })
    }

    public func updateBacktestResult(
      request: UpdateBacktestResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBacktestResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBacktestResult(request: r, options: o)
        })
    }

    public func exportBacktestResultMetadata(
      request: ExportBacktestResultMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportBacktestResultMetadataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportBacktestResultMetadata(request: r, options: o)
        })
    }

    public func deleteBacktestResult(
      request: DeleteBacktestResultRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBacktestResultRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBacktestResult(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
