// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// BacktestResult is created to test the performance of a model on a dataset.
public struct BacktestResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the BacktestResult.
  /// format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/backtestResults/{backtest_result}`
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp of creation of this resource.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp of the most recent update of this resource.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Labels
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State of the BacktestResult (creating, active, deleting, etc.)
  public var state: BacktestResult.State = BacktestResult.State()

  /// Required. The resource name of the Dataset to backtest on
  /// Format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/datasets/{dataset}`
  public var dataset: Swift.String = Swift.String()

  /// Required. The resource name of the Model to use or to backtest.
  /// Format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/models/{model}`
  public var model: Swift.String = Swift.String()

  /// Required. End_time specifies the latest time from which labels are used and
  /// from which data is used to generate features for backtesting.  End_time
  /// should be no later than the end of the date_range of the primary dataset.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// The number of consecutive months to conduct backtesting for, ending with
  /// the last full month prior to the end_time according to the dataset's
  /// timezone.
  public var backtestPeriods: Swift.Int32 = Swift.Int32()

  /// Required. PerformanceTarget gives information on how the test will be
  /// evaluated.
  public var performanceTarget: BacktestResult.PerformanceTarget? = nil

  /// Output only. The line of business (Retail/Commercial) this backtest is for.
  /// Determined by Model, cannot be set by user.
  public var lineOfBusiness: LineOfBusiness = LineOfBusiness()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BacktestResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BacktestResult().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let dataset = CodingKeys(stringValue: "dataset")
    static let model = CodingKeys(stringValue: "model")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let backtestPeriods = CodingKeys(stringValue: "backtestPeriods")
    static let performanceTarget = CodingKeys(stringValue: "performanceTarget")
    static let lineOfBusiness = CodingKeys(stringValue: "lineOfBusiness")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "state",
      "dataset",
      "model",
      "endTime",
      "backtestPeriods",
      "performanceTarget",
      "lineOfBusiness",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(BacktestResult.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataset) {
      self.dataset = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backtestPeriods) {
      self.backtestPeriods = value
    }
    self.performanceTarget = try container.decodeIfPresent(
      BacktestResult.PerformanceTarget.self, forKey: .performanceTarget)
    if let value = try container.decodeIfPresent(LineOfBusiness.self, forKey: .lineOfBusiness) {
      self.lineOfBusiness = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.dataset, forKey: .dataset)
    try container.encode(self.model, forKey: .model)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.backtestPeriods, forKey: .backtestPeriods)
    try container.encodeIfPresent(self.performanceTarget, forKey: .performanceTarget)
    try container.encode(self.lineOfBusiness, forKey: .lineOfBusiness)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// PerformanceTarget gives hints on how to evaluate the performance of a
  /// model.
  public struct PerformanceTarget: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. A number that gives the tuner a hint on the number of parties
    /// from this data that will be investigated per period (monthly). This is
    /// used to control how the model is evaluated. For example, when trying AML
    /// AI for the first time, we recommend setting this to the number of parties
    /// investigated in an average month, based on alerts from your existing
    /// automated alerting system.
    public var partyInvestigationsPerPeriodHint: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PerformanceTarget`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PerformanceTarget().with { $0.partyInvestigationsPerPeriodHint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let partyInvestigationsPerPeriodHint = CodingKeys(
        stringValue: "partyInvestigationsPerPeriodHint")

      static let _knownKeys: Set<Swift.String> = [
        "partyInvestigationsPerPeriodHint"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .partyInvestigationsPerPeriodHint)
      {
        self.partyInvestigationsPerPeriodHint = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(
        self.partyInvestigationsPerPeriodHint, forKey: .partyInvestigationsPerPeriodHint)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.financialservices.v1.BacktestResult.PerformanceTarget"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible states of a resource.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// State is unspecified, should not occur.
    case unspecified
    /// The resource has not finished being created.
    case creating
    /// The resource is active/ready to be used.
    case active
    /// The resource is in the process of being updated.
    case updating
    /// The resource is in the process of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.BacktestResult"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
