// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// BigQueryDestination is a wrapper for BigQuery output information.
public struct BigQueryDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. BigQuery URI to a table, must be of the form
  /// bq://projectId.bqDatasetId.tableId.
  /// Note that the BigQuery dataset must already exist.
  /// VPC-SC restrictions apply.
  public var tableUri: Swift.String = Swift.String()

  /// Required. Whether or not to overwrite the destination table. By default the
  /// table won't be overwritten and an error will be returned if the table
  /// exists and contains data.
  public var writeDisposition: BigQueryDestination.WriteDisposition =
    BigQueryDestination.WriteDisposition()

  /// Initialize a new instance of `BigQueryDestination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryDestination().with { $0.tableUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// WriteDisposition controls the behavior when the destination table already
  /// exists.
  public enum WriteDisposition: Codable, Equatable, Sendable {
    /// Default behavior is the same as WRITE_EMPTY.
    case unspecified
    /// If the table already exists and contains data, an error is returned.
    case writeEmpty
    /// If the table already exists, the data will be overwritten.
    case writeTruncate
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .writeEmpty: return 1
      case .writeTruncate: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WRITE_DISPOSITION_UNSPECIFIED"
      case .writeEmpty: return "WRITE_EMPTY"
      case .writeTruncate: return "WRITE_TRUNCATE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WriteDisposition/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WRITE_DISPOSITION_UNSPECIFIED": self = .unspecified
      case "WRITE_EMPTY": self = .writeEmpty
      case "WRITE_TRUNCATE": self = .writeTruncate
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WriteDisposition/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .writeEmpty
      case 2: self = .writeTruncate
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .writeEmpty: return try container.encode(1)
      case .writeTruncate: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.BigQueryDestination"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
