// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The EngineConfig resource creates the configuration for training a model.
public struct EngineConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the EngineConfig.
  /// format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/engineConfigs/{engine_config}`
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp of creation of this resource.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp of the most recent update of this resource.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Labels
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State of the EngineConfig (creating, active, deleting, etc.)
  public var state: EngineConfig.State = EngineConfig.State()

  /// Required. The resource name of the EngineVersion used in this model tuning.
  /// format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/engineVersions/{engine_version}`
  public var engineVersion: Swift.String = Swift.String()

  /// Optional. Configuration for tuning in creation of the EngineConfig.
  /// This field is required if `hyperparameter_source.type` is not `INHERITED`,
  /// and output-only otherwise.
  public var tuning: EngineConfig.Tuning? = nil

  /// Optional. PerformanceTarget gives information on how the tuning and
  /// training will be evaluated. This field is required if
  /// `hyperparameter_source.type` is not `INHERITED`, and output-only otherwise.
  public var performanceTarget: EngineConfig.PerformanceTarget? = nil

  /// Output only. The line of business (Retail/Commercial) this engine config is
  /// used for. Determined by EngineVersion, cannot be set by user.
  public var lineOfBusiness: LineOfBusiness = LineOfBusiness()

  /// Optional. The origin of hyperparameters for the created EngineConfig. The
  /// default is `TUNING`. In this case, the hyperparameters are selected as a
  /// result of a
  ///  tuning run.
  public var hyperparameterSourceType: EngineConfig.HyperparameterSourceType =
    EngineConfig.HyperparameterSourceType()

  /// Optional. Configuration of hyperparameters source EngineConfig.
  public var hyperparameterSource: EngineConfig.HyperparameterSource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EngineConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EngineConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let engineVersion = CodingKeys(stringValue: "engineVersion")
    static let tuning = CodingKeys(stringValue: "tuning")
    static let performanceTarget = CodingKeys(stringValue: "performanceTarget")
    static let lineOfBusiness = CodingKeys(stringValue: "lineOfBusiness")
    static let hyperparameterSourceType = CodingKeys(stringValue: "hyperparameterSourceType")
    static let hyperparameterSource = CodingKeys(stringValue: "hyperparameterSource")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "state",
      "engineVersion",
      "tuning",
      "performanceTarget",
      "lineOfBusiness",
      "hyperparameterSourceType",
      "hyperparameterSource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(EngineConfig.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .engineVersion) {
      self.engineVersion = value
    }
    self.tuning = try container.decodeIfPresent(EngineConfig.Tuning.self, forKey: .tuning)
    self.performanceTarget = try container.decodeIfPresent(
      EngineConfig.PerformanceTarget.self, forKey: .performanceTarget)
    if let value = try container.decodeIfPresent(LineOfBusiness.self, forKey: .lineOfBusiness) {
      self.lineOfBusiness = value
    }
    if let value = try container.decodeIfPresent(
      EngineConfig.HyperparameterSourceType.self, forKey: .hyperparameterSourceType)
    {
      self.hyperparameterSourceType = value
    }
    self.hyperparameterSource = try container.decodeIfPresent(
      EngineConfig.HyperparameterSource.self, forKey: .hyperparameterSource)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.engineVersion, forKey: .engineVersion)
    try container.encodeIfPresent(self.tuning, forKey: .tuning)
    try container.encodeIfPresent(self.performanceTarget, forKey: .performanceTarget)
    try container.encode(self.lineOfBusiness, forKey: .lineOfBusiness)
    try container.encode(self.hyperparameterSourceType, forKey: .hyperparameterSourceType)
    try container.encodeIfPresent(self.hyperparameterSource, forKey: .hyperparameterSource)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The parameters needed for the tuning operation, these are used only in
  /// tuning and not passed on to training.
  public struct Tuning: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the Primary Dataset used in this model
    /// tuning. For information about how primary and auxiliary datasets are
    /// used, refer to the engine version's documentation.  Format:
    /// `/projects/{project_num}/locations/{location}/instances/{instance}/datasets/{dataset}`
    public var primaryDataset: Swift.String = Swift.String()

    /// Required. End_time specifies the latest time from which labels are used
    /// and from which data is used to generate features for tuning.  End_time
    /// should be no later than the end of the date_range of the dataset.
    public var endTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Tuning`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tuning().with { $0.primaryDataset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let primaryDataset = CodingKeys(stringValue: "primaryDataset")
      static let endTime = CodingKeys(stringValue: "endTime")

      static let _knownKeys: Set<Swift.String> = [
        "primaryDataset",
        "endTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primaryDataset) {
        self.primaryDataset = value
      }
      self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.primaryDataset, forKey: .primaryDataset)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.financialservices.v1.EngineConfig.Tuning"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// PerformanceTarget gives hints on how to evaluate the performance of a
  /// model.
  public struct PerformanceTarget: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. A number that gives the tuner a hint on the number of parties
    /// from this data that will be investigated per period (monthly). This is
    /// used to control how the model is evaluated. For example, when trying AML
    /// AI for the first time, we recommend setting this to the number of parties
    /// investigated in an average month, based on alerts from your existing
    /// automated alerting system.
    public var partyInvestigationsPerPeriodHint: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PerformanceTarget`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PerformanceTarget().with { $0.partyInvestigationsPerPeriodHint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let partyInvestigationsPerPeriodHint = CodingKeys(
        stringValue: "partyInvestigationsPerPeriodHint")

      static let _knownKeys: Set<Swift.String> = [
        "partyInvestigationsPerPeriodHint"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.Int64.self, forKey: .partyInvestigationsPerPeriodHint)
      {
        self.partyInvestigationsPerPeriodHint = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(
        self.partyInvestigationsPerPeriodHint, forKey: .partyInvestigationsPerPeriodHint)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.financialservices.v1.EngineConfig.PerformanceTarget"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters for bootstrapping an Engine Config with the results of another
  /// one.
  public struct HyperparameterSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The resource name of the source EngineConfig whose outputs are
    /// used. Format:
    /// `/projects/{project_num}/locations/{location}/instances/{instance}/engineConfigs/{engine_config}`
    public var sourceEngineConfig: Swift.String = Swift.String()

    /// Output only. The resource name of the EngineVersion that was used in the
    /// tuning run. Format:
    /// `/projects/{project_num}/locations/{location}/instances/{instance}/engineVersions/{engine_version}`
    public var sourceEngineVersion: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `HyperparameterSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HyperparameterSource().with { $0.sourceEngineConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceEngineConfig = CodingKeys(stringValue: "sourceEngineConfig")
      static let sourceEngineVersion = CodingKeys(stringValue: "sourceEngineVersion")

      static let _knownKeys: Set<Swift.String> = [
        "sourceEngineConfig",
        "sourceEngineVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceEngineConfig) {
        self.sourceEngineConfig = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceEngineVersion)
      {
        self.sourceEngineVersion = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceEngineConfig, forKey: .sourceEngineConfig)
      try container.encode(self.sourceEngineVersion, forKey: .sourceEngineVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.financialservices.v1.EngineConfig.HyperparameterSource"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The possible states of a resource.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// State is unspecified, should not occur.
    case unspecified
    /// The resource has not finished being created.
    case creating
    /// The resource is active/ready to be used.
    case active
    /// The resource is in the process of being updated.
    case updating
    /// The resource is in the process of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of the hyperparameter source.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum HyperparameterSourceType: Codable, Equatable, Sendable {
    /// Hyperparameter source type is unspecified, defaults to TUNING.
    case unspecified
    /// The EngineConfig creation starts a tuning job which selects the best
    /// hyperparameters.
    case tuning
    /// The hyperparameters are inherited from another EngineConfig.
    case inherited
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .tuning: return 1
      case .inherited: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HYPERPARAMETER_SOURCE_TYPE_UNSPECIFIED"
      case .tuning: return "TUNING"
      case .inherited: return "INHERITED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HyperparameterSourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HYPERPARAMETER_SOURCE_TYPE_UNSPECIFIED": self = .unspecified
      case "TUNING": self = .tuning
      case "INHERITED": self = .inherited
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HyperparameterSourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .tuning
      case 2: self = .inherited
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("HYPERPARAMETER_SOURCE_TYPE_UNSPECIFIED")
      case .tuning: return try container.encode("TUNING")
      case .inherited: return try container.encode("INHERITED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.EngineConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
