// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for adding/removing registered parties from BigQuery tables
/// specified by the customer.
public struct ImportRegisteredPartiesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The full path to the Instance resource in this API.
  /// format: `projects/{project}/locations/{location}/instances/{instance}`
  public var name: Swift.String = Swift.String()

  /// Optional. List of BigQuery tables. Union of tables will be taken if there
  /// is more than one table. VPC-SC restrictions apply. format:
  /// `bq://{project}.{bqDatasetID}.{bqTableID}` Use of `datasets` is preferred
  /// over the latter due to its simplicity and the reduced risk of errors
  /// `party_tables` and `datasets` must not be provided at the
  /// same time
  public var partyTables: [Swift.String] = []

  /// Required. Mode of the request.
  public var mode: ImportRegisteredPartiesRequest.UpdateMode =
    ImportRegisteredPartiesRequest.UpdateMode()

  /// Optional. If the request will not register the parties, just determine what
  /// would happen.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Required. LineOfBusiness for the specified registered parties.
  public var lineOfBusiness: LineOfBusiness = LineOfBusiness()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportRegisteredPartiesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportRegisteredPartiesRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let partyTables = CodingKeys(stringValue: "partyTables")
    static let mode = CodingKeys(stringValue: "mode")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let lineOfBusiness = CodingKeys(stringValue: "lineOfBusiness")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "partyTables",
      "mode",
      "validateOnly",
      "lineOfBusiness",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .partyTables) {
      self.partyTables = value
    }
    if let value = try container.decodeIfPresent(
      ImportRegisteredPartiesRequest.UpdateMode.self, forKey: .mode)
    {
      self.mode = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent(LineOfBusiness.self, forKey: .lineOfBusiness) {
      self.lineOfBusiness = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.partyTables, forKey: .partyTables)
    try container.encode(self.mode, forKey: .mode)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.lineOfBusiness, forKey: .lineOfBusiness)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// UpdateMode controls the behavior for ImportRegisteredParties.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum UpdateMode: Codable, Equatable, Sendable {
    /// Default mode.
    case unspecified
    /// Replace parties that are removable in Parties Table with new parties.
    case replace
    /// Add new parties to Parties Table.
    case append
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .replace: return 1
      case .append: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UPDATE_MODE_UNSPECIFIED"
      case .replace: return "REPLACE"
      case .append: return "APPEND"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UpdateMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UPDATE_MODE_UNSPECIFIED": self = .unspecified
      case "REPLACE": self = .replace
      case "APPEND": self = .append
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UpdateMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .replace
      case 2: self = .append
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("UPDATE_MODE_UNSPECIFIED")
      case .replace: return try container.encode("REPLACE")
      case .append: return try container.encode("APPEND")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.ImportRegisteredPartiesRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
