// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response for adding/removing registered parties from BigQuery tables.
public struct ImportRegisteredPartiesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Number of parties added by this operation.
  public var partiesAdded: Swift.Int64 = Swift.Int64()

  /// Number of parties removed by this operation.
  public var partiesRemoved: Swift.Int64 = Swift.Int64()

  /// Total number of parties that are registered in this instance, after the
  /// update operation was completed.
  public var partiesTotal: Swift.Int64 = Swift.Int64()

  /// Number of parties that failed to be removed by this operation.
  public var partiesFailedToRemove: Swift.Int64 = Swift.Int64()

  public var partiesUptiered: Swift.Int64 = Swift.Int64()

  /// Total number of parties that are downtiered in this instance
  public var partiesDowntiered: Swift.Int64 = Swift.Int64()

  /// Number of parties that failed to be downtiered
  public var partiesFailedToDowntier: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `ImportRegisteredPartiesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportRegisteredPartiesResponse().with { $0.partiesAdded = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.ImportRegisteredPartiesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
