// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response for adding/removing registered parties from BigQuery tables.
public struct ImportRegisteredPartiesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Number of parties added by this operation.
  public var partiesAdded: Swift.Int64 = Swift.Int64()

  /// Number of parties removed by this operation.
  public var partiesRemoved: Swift.Int64 = Swift.Int64()

  /// Total number of parties that are registered in this instance, after the
  /// update operation was completed.
  public var partiesTotal: Swift.Int64 = Swift.Int64()

  /// Number of parties that failed to be removed by this operation.
  public var partiesFailedToRemove: Swift.Int64 = Swift.Int64()

  public var partiesUptiered: Swift.Int64 = Swift.Int64()

  /// Total number of parties that are downtiered in this instance
  public var partiesDowntiered: Swift.Int64 = Swift.Int64()

  /// Number of parties that failed to be downtiered
  public var partiesFailedToDowntier: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ImportRegisteredPartiesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportRegisteredPartiesResponse().with { $0.partiesAdded = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let partiesAdded = CodingKeys(stringValue: "partiesAdded")
    static let partiesRemoved = CodingKeys(stringValue: "partiesRemoved")
    static let partiesTotal = CodingKeys(stringValue: "partiesTotal")
    static let partiesFailedToRemove = CodingKeys(stringValue: "partiesFailedToRemove")
    static let partiesUptiered = CodingKeys(stringValue: "partiesUptiered")
    static let partiesDowntiered = CodingKeys(stringValue: "partiesDowntiered")
    static let partiesFailedToDowntier = CodingKeys(stringValue: "partiesFailedToDowntier")

    static let _knownKeys: Set<Swift.String> = [
      "partiesAdded",
      "partiesRemoved",
      "partiesTotal",
      "partiesFailedToRemove",
      "partiesUptiered",
      "partiesDowntiered",
      "partiesFailedToDowntier",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesAdded) {
      self.partiesAdded = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesRemoved) {
      self.partiesRemoved = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesTotal) {
      self.partiesTotal = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesFailedToRemove) {
      self.partiesFailedToRemove = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesUptiered) {
      self.partiesUptiered = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesDowntiered) {
      self.partiesDowntiered = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .partiesFailedToDowntier)
    {
      self.partiesFailedToDowntier = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.partiesAdded, forKey: .partiesAdded)
    try container.encode(self.partiesRemoved, forKey: .partiesRemoved)
    try container.encode(self.partiesTotal, forKey: .partiesTotal)
    try container.encode(self.partiesFailedToRemove, forKey: .partiesFailedToRemove)
    try container.encode(self.partiesUptiered, forKey: .partiesUptiered)
    try container.encode(self.partiesDowntiered, forKey: .partiesDowntiered)
    try container.encode(self.partiesFailedToDowntier, forKey: .partiesFailedToDowntier)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.ImportRegisteredPartiesResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
