// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for retrieving a paginated list of EngineVersion resources that meet
/// the specified criteria.
public struct ListEngineVersionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent of the EngineVersion is the Instance.
  public var parent: Swift.String = Swift.String()

  /// Optional. The number of resources to be included in the response. The
  /// response contains a next_page_token, which can be used to retrieve the next
  /// page of resources.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. In case of paginated results, this is the token that was returned
  /// in the previous ListEngineVersionsResponse. It should be copied here to
  /// retrieve the next page of resources. Empty will give the first page of
  /// ListEngineVersionsRequest, and the last page will return an empty
  /// page_token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Specify a filter to narrow search results.
  /// If empty or unset will default to "state!=DEPRECATED",
  /// to view deprecated versions use "state:*" or any other filter.
  public var filter: Swift.String = Swift.String()

  /// Optional. Specify a field to use for ordering.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEngineVersionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEngineVersionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.ListEngineVersionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
