// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Model represents a trained model.
public struct Model: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the Model.
  /// format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/models/{model}`
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp of creation of this resource.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp of the most recent update of this resource.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. State of the model (creating, active, deleting, etc.)
  public var state: Model.State = Model.State()

  /// Output only. The EngineVersion used in training this model.  This is output
  /// only, and is determined from the EngineConfig used.
  public var engineVersion: Swift.String = Swift.String()

  /// Required. The resource name of the EngineConfig the model training will be
  /// based on. Format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/engineConfigs/{engineConfig}`
  public var engineConfig: Swift.String = Swift.String()

  /// Required. The resource name of the Primary Dataset used in this model
  /// training. For information about how primary and auxiliary datasets are
  /// used, refer to the engine version's documentation.  Format:
  /// `/projects/{project_num}/locations/{location}/instances/{instance}/datasets/{dataset}`
  public var primaryDataset: Swift.String = Swift.String()

  /// Required. End_time specifies the latest time from which labels are used and
  /// from which data is used to generate features for training.  End_time should
  /// be no later than the end of the date_range of the dataset.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The line of business (Retail/Commercial) this model is used
  /// for. Determined by EngineConfig, cannot be set by user.
  public var lineOfBusiness: LineOfBusiness = LineOfBusiness()

  /// Initialize a new instance of `Model`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Model().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible states of a resource.
  public enum State: Codable, Equatable, Sendable {
    /// State is unspecified, should not occur.
    case unspecified
    /// The resource has not finished being created.
    case creating
    /// The resource is active/ready to be used.
    case active
    /// The resource is in the process of being updated.
    case updating
    /// The resource is in the process of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .updating: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.financialservices.v1.Model"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
